### ISSUE TITLE
关于requirements的一下小问题

### ISSUE THREAD

**Issue by Agrion613** [Firesuiry/RLAM-OPENSOURSE#1]
作者您好，我最近在拜读您的论文并想看看代码效果时，发现您的requirements中有的软件包并不显示版本号，我查看了一下是pip的原因，详见下述csdn地址：https://blog.csdn.net/qq_38048756/article/details/115337465，如果您看到，可以重新生成一下requirements吗？万分感谢！

![问题](https://github.com/Firesuiry/RLAM-OPENSOURSE/assets/71387870/98420128-bcc6-4bce-a94f-c71bf7d96443)

**Comment by rodrigoclira** [comment]
I faced the same issue. The `requirements.txt` from the repository is using local files that we do not have access.

You can use this one  https://github.com/rodrigoclira/RLAM-OPENSOURSE/blob/master/requirements.txt
It is possible that you can need to install more modules to enable other features, but you will be able to run the main code with this one.

**Comment by Firesuiry** [comment]
> I faced the same issue. The `requirements.txt` from the repository is using local files that we do not have access.
> 
> You can use this one https://github.com/rodrigoclira/RLAM-OPENSOURSE/blob/master/requirements.txt It is possible that you can need to install more modules to enable other features, but you will be able to run the main code with this one.

Thank you~
