### ISSUE TITLE
How to configure the simulation hyperparameters?

### ISSUE THREAD

**Issue by rodrigoclira** [Firesuiry/RLAM-OPENSOURSE#2]
Dear, 

Could you please tell me how I can configure the code to run a simple experiment with few benchmark functions and low number of dimensions? I'm able to run it, but I cannot see the end of the simulation, and I guess that it happens because the code runs a huge number of functions.

**Comment by Firesuiry** [comment]
you can configure it in task/all_tasks_generate.py

in line 46 (function def all_tasks_generate())
以下是最小可以运行的参数组,可以按照以下给出的参数运行
runtimes can be 1 意味着运行1次
evaluate_optimizers 设置为 [PsoSwarm] 意味着仅运行原始PSO（这个是原始方法）
base_evaluate_optimizers  设置为 [PsoSwarm] 意味着仅运行原始PSO（这个是结合了RLAM之后的方法）
separate_trains = [True, ] 表示对每个测试函数进行分别训练
train_max_episode = 1 意味只训练一轮
dims = [30,] 意味着只在30D上运行
evaluate_function = [1,] 意味着只测试函数1

全部运行完成后会生成xls文件 在data文件夹中

**Comment by rodrigoclira** [comment]
Thank you, @Firesuiry ! 
I was wondering about the computational cost to run it... 
Could you please give me a guess? Is it about hours or days? 

Please, consider a normal simulation.

**Comment by Firesuiry** [comment]
> Thank you, @Firesuiry ! I was wondering about the computational cost to run it... Could you please give me a guess? Is it about hours or days?
> 
> Please, consider a normal simulation.

 我当时运行的时候 用的是一个有48个核心的服务器，所有测试跑完总运行时间大概需要4-5天。（记得不清楚了，大概是这样子的）

**Comment by Firesuiry** [comment]
主要是运行的轮数多，还有对每个测试函数进行训练，测试花费时间很长。

**Comment by rodrigoclira** [comment]
> 主要是运行的轮数多，还有对每个测试函数进行训练，测试花费时间很长。

I see. Thank you for the information.
I'll close the issue.
